import test from 'node:test';import assert from 'node:assert/strict';
import { createReaderSpeech,koreanLocalVoice,speechChunks } from '../src/student/speech.ts';
const local={lang:'ko-KR',localService:true,name:'local Korean'};
function fixture(timeout=1000) {let epoch=0,cancels=0,pauses=0,resumes=0;const spoken:any[]=[];const views:any[]=[];
 const controller=createReaderSpeech({getEpoch:()=>epoch,voices:()=>[local],utterance:text=>({text,voice:null,lang:'',rate:1,onend:null,onerror:null}),speak:value=>{spoken.push(value)},cancel:()=>{cancels++},pause:()=>{pauses++},resume:()=>{resumes++},changed:v=>views.push(v),maxChunkMs:timeout});
 return {controller,spoken,views,change:()=>epoch++,counts:()=>({cancels,pauses,resumes})};}
test('voice selection never falls back to remote Korean or local English',()=>{assert.equal(koreanLocalVoice([{...local,localService:false},{...local,lang:'en-US'}]),undefined);assert.equal(koreanLocalVoice([{...local,localService:false},local]),local)});
test('bounded Unicode chunks retain emoji, cap 10000 codepoints and never loop',()=>{const x=speechChunks('🙂'.repeat(11000));assert.equal(x.chunks.length,46);assert.equal(x.truncated,true);assert.equal(Array.from(x.chunks.join('')).length,10000)});
test('speech is opt-in and uses explicit local voice, pause/resume/stop controls',()=>{const f=fixture();assert.equal(f.spoken.length,0);f.controller.start('본문');assert.equal(f.spoken[0].voice,local);assert.equal(f.spoken[0].lang,'ko-KR');f.controller.pause();assert.equal(f.controller.getView().state,'paused');f.controller.resume();assert.equal(f.controller.getView().state,'speaking');f.controller.stop();assert.equal(f.controller.getView().state,'idle');assert.equal(f.counts().pauses,1);assert.equal(f.counts().resumes,1);f.controller.dispose()});
test('each utterance end settles once and queues only one next chunk',()=>{const f=fixture();f.controller.start('가'.repeat(221));const first=f.spoken[0];first.onend();first.onend();assert.equal(f.spoken.length,2);f.spoken[1].onend();assert.equal(f.controller.getView().state,'idle');f.controller.dispose()});
test('stop, route disposal and logout prevent late callbacks from enqueueing',()=>{for(const action of ['stop','dispose','logout']){const f=fixture();f.controller.start('가'.repeat(221));if(action==='logout')f.change();else if(action==='dispose')f.controller.dispose();else f.controller.stop();f.spoken[0].onend();assert.equal(f.spoken.length,1);f.controller.dispose()}});
test('missing voice and thrown speech API expose limitation without remote fallback',()=>{let calls=0;const c=createReaderSpeech({getEpoch:()=>0,voices:()=>[{...local,localService:false}],utterance:()=>{throw Error()},speak:()=>{calls++},cancel:()=>{},pause:()=>{},resume:()=>{},changed:()=>{}});c.start('본문');assert.equal(c.getView().state,'unavailable');assert.equal(calls,0);c.dispose()});
test('speech errors and missing callback have bounded failure',async()=>{const f=fixture(2);f.controller.start('본문');await new Promise(r=>setTimeout(r,8));assert.equal(f.controller.getView().state,'error');f.spoken[0].onend();assert.equal(f.controller.getView().state,'error');f.controller.dispose();const g=fixture();g.controller.start('본문');g.spoken[0].onerror();assert.equal(g.controller.getView().state,'error');g.controller.dispose()});
test('paused speech does not time out while waiting for user; resumed playback remains bounded',async()=>{const f=fixture(3);f.controller.start('본문');f.controller.pause();await new Promise(r=>setTimeout(r,10));assert.equal(f.controller.getView().state,'paused');f.controller.resume();await new Promise(r=>setTimeout(r,10));assert.equal(f.controller.getView().state,'error');f.controller.dispose()});
