import test from 'node:test';import assert from 'node:assert/strict';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
import {chapters,questions,source,studentIndex,identity,plainText,modeLabel,gradingModeLabel} from '../src/student/model.ts';
test('allowlisted chapter extraction omits quiz/answer/URL fields and never constructs HTML',()=>{const parsed=chapters({chapters:[{id:'a',type:'content',title:'제목',content:'<p>본문</p><img src="https://external.invalid/image"><script>alert(1)</script>'},{id:'q',type:'quiz',title:'비공개',correctAnswer:'정답'}],teacherAnswer:'비공개'});assert.deepEqual(parsed,[{id:'a',title:'제목',text:'본문'}]);assert.equal(renderToStaticMarkup(React.createElement('p',{},plainText('&lt;img src=x onerror=alert(1)&gt;'))).includes('<img'),false)});
test('student question parser copies only public problem/version fields',()=>{const parsed=questions([{id:1,version:0,content:'문제',question_number:1,title:'퀴즈',correct_answer:'secret',ai_feedback:'secret'}]);assert.deepEqual(Object.keys(parsed[0]).sort(),['content','id','question_number','title','version']);assert.throws(()=>questions([{id:1,content:'missing version',question_number:1}]))});
test('unknown indexing never enables learning; queued is not active',()=>{assert.equal(studentIndex({state:'QUEUED',readable:false,activeCurrent:false,sourceRevision:1})?.readable,false);assert.equal(studentIndex({state:'READY',readable:true,activeCurrent:true,sourceRevision:1}),null);assert.equal(studentIndex({state:'SUCCEEDED',readable:false,activeCurrent:true,sourceRevision:1}),null)});
test('source identity and hashes must match a real material contract',()=>{const s={document_id:'7',source_revision:2,source_hash:'a'.repeat(64),content_hash:'b'.repeat(64),chunk_position:0,material_title:'교재',excerpt:'실제 발췌'};assert.deepEqual(source({...s,private_path:'hidden'},7),s);assert.throws(()=>source(s,8));assert.throws(()=>source({...s,source_hash:'invalid'},7))});
test('server identity is validated instead of trusting browser role hints',()=>{assert.equal(identity({userId:7,name:'합성 학생',role:'STUDENT',demo:true}).role,'STUDENT');assert.throws(()=>identity({userId:7,name:'x',role:'ADMIN',demo:true}));assert.throws(()=>identity({userId:'7',name:'x',role:'STUDENT',demo:true}))});
test('missing mode is never labelled as verified real AI',()=>{assert.match(modeLabel(null),/확인 필요/);assert.match(modeLabel({environment:'local',answer_provider:'local_stub',embedding_provider:'local_hash8',grading_provider:'local_stub'}),/로컬 대역/)});

test('partial provider configurations keep independent labels and never claim verified quality',()=>{const partial={environment:'local',answer_provider:'live_openai',embedding_provider:'local_hash8',grading_provider:'local_stub'};assert.match(modeLabel(partial),/OpenAI 답변 설정/);assert.match(modeLabel(partial),/8차원 로컬/);assert.match(gradingModeLabel(partial),/로컬 대역 채점/);assert.match(gradingModeLabel({...partial,grading_provider:'live_openai'}),/OpenAI 채점 설정/);assert.doesNotMatch(modeLabel(partial),/전체 실제|검증 완료/);assert.match(modeLabel({...partial,embedding_provider:'unknown'}),/임베딩 모드 확인 필요/)});
